//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  G:\NewCode\PorousGen\UG_Dev\Application\Porous2D.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: Turbine00
//              Version: NX 1919
//              Date: 09-04-2021  (Format: mm-dd-yyyy)
//              Time: 15:47
//
//==============================================================================

#ifndef POROUS2D_H_INCLUDED
#define POROUS2D_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_SpecifyPoint.hxx>
#include <NXOpen/BlockStyler_Enumeration.hxx>
#include <NXOpen/BlockStyler_Toggle.hxx>
#include <NXOpen/BlockStyler_TabControl.hxx>
#include <NXOpen/BlockStyler_ExpressionBlock.hxx>
#include <NXOpen/BlockStyler_IntegerBlock.hxx>
#include <NXOpen/BlockStyler_DoubleBlock.hxx>
#include <NXOpen/BlockStyler_Button.hxx>
#include <NXOpen/BlockStyler_FolderSelection.hxx>

//------------------------------------------------------------------------------
//Bit Option for Property: SnapPointTypesEnabled
//------------------------------------------------------------------------------
#define              SnapPointTypesEnabled_UserDefined (1 << 0);
#define                 SnapPointTypesEnabled_Inferred (1 << 1);
#define           SnapPointTypesEnabled_ScreenPosition (1 << 2);
#define                 SnapPointTypesEnabled_EndPoint (1 << 3);
#define                 SnapPointTypesEnabled_MidPoint (1 << 4);
#define             SnapPointTypesEnabled_ControlPoint (1 << 5);
#define             SnapPointTypesEnabled_Intersection (1 << 6);
#define                SnapPointTypesEnabled_ArcCenter (1 << 7);
#define            SnapPointTypesEnabled_QuadrantPoint (1 << 8);
#define            SnapPointTypesEnabled_ExistingPoint (1 << 9);
#define             SnapPointTypesEnabled_PointonCurve (1 <<10);
#define           SnapPointTypesEnabled_PointonSurface (1 <<11);
#define         SnapPointTypesEnabled_PointConstructor (1 <<12);
#define     SnapPointTypesEnabled_TwocurveIntersection (1 <<13);
#define             SnapPointTypesEnabled_TangentPoint (1 <<14);
#define                    SnapPointTypesEnabled_Poles (1 <<15);
#define         SnapPointTypesEnabled_BoundedGridPoint (1 <<16);
#define         SnapPointTypesEnabled_FacetVertexPoint (1 <<17);
#define            SnapPointTypesEnabled_DefiningPoint (1 <<18);
//------------------------------------------------------------------------------
//Bit Option for Property: SnapPointTypesOnByDefault
//------------------------------------------------------------------------------
#define          SnapPointTypesOnByDefault_UserDefined (1 << 0);
#define             SnapPointTypesOnByDefault_Inferred (1 << 1);
#define       SnapPointTypesOnByDefault_ScreenPosition (1 << 2);
#define             SnapPointTypesOnByDefault_EndPoint (1 << 3);
#define             SnapPointTypesOnByDefault_MidPoint (1 << 4);
#define         SnapPointTypesOnByDefault_ControlPoint (1 << 5);
#define         SnapPointTypesOnByDefault_Intersection (1 << 6);
#define            SnapPointTypesOnByDefault_ArcCenter (1 << 7);
#define        SnapPointTypesOnByDefault_QuadrantPoint (1 << 8);
#define        SnapPointTypesOnByDefault_ExistingPoint (1 << 9);
#define         SnapPointTypesOnByDefault_PointonCurve (1 <<10);
#define       SnapPointTypesOnByDefault_PointonSurface (1 <<11);
#define     SnapPointTypesOnByDefault_PointConstructor (1 <<12);
#define SnapPointTypesOnByDefault_TwocurveIntersection (1 <<13);
#define         SnapPointTypesOnByDefault_TangentPoint (1 <<14);
#define                SnapPointTypesOnByDefault_Poles (1 <<15);
#define     SnapPointTypesOnByDefault_BoundedGridPoint (1 <<16);
#define     SnapPointTypesOnByDefault_FacetVertexPoint (1 <<17);
#define        SnapPointTypesOnByDefault_DefiningPoint (1 <<18);
//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport Porous2D
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    Porous2D();
    ~Porous2D();
    int Show();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the Porous2D.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);
    
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* groupSheetStartPoint;// Block type: Group
    NXOpen::BlockStyler::SpecifyPoint* pointSheetStart;// Block type: Specify Point
    NXOpen::BlockStyler::Group* groupShape;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enumParticleShape;// Block type: Enumeration
    NXOpen::BlockStyler::Group* groupGenMethod;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enumGenMethod;// Block type: Enumeration
    NXOpen::BlockStyler::Toggle* toggleMeshRandom;// Block type: Toggle
    NXOpen::BlockStyler::Group* groupSize;// Block type: Group
    NXOpen::BlockStyler::TabControl* tabControl1;// Block type: Tabs Page
    NXOpen::BlockStyler::Group* tabPage2;
    NXOpen::BlockStyler::ExpressionBlock* expressionFaceLength;// Block type: Expression
    NXOpen::BlockStyler::ExpressionBlock* expressionFaceWidth;// Block type: Expression
    NXOpen::BlockStyler::ExpressionBlock* expressionParticleSize;// Block type: Expression
    NXOpen::BlockStyler::Group* tabPage3;
    NXOpen::BlockStyler::ExpressionBlock* expressionBasisWeight;// Block type: Expression
    NXOpen::BlockStyler::ExpressionBlock* expressionDryContentFinal;// Block type: Expression
    NXOpen::BlockStyler::ExpressionBlock* expressionDryContentNow;// Block type: Expression
    NXOpen::BlockStyler::ExpressionBlock* expressionSheetLen;// Block type: Expression
    NXOpen::BlockStyler::Group* tabPage4;
    NXOpen::BlockStyler::ExpressionBlock* expressionLenDensity;// Block type: Expression
    NXOpen::BlockStyler::ExpressionBlock* expressionCelLength;// Block type: Expression
    NXOpen::BlockStyler::ExpressionBlock* expressionCelDiameter;// Block type: Expression
    NXOpen::BlockStyler::ExpressionBlock* expressionLenWidRatio;// Block type: Expression
    NXOpen::BlockStyler::Toggle* togglePaper;// Block type: Toggle
    NXOpen::BlockStyler::ExpressionBlock* expressionComRatio;// Block type: Expression
    NXOpen::BlockStyler::Group* groupParticle;// Block type: Group
    NXOpen::BlockStyler::TabControl* tabControl;// Block type: Tabs Page
    NXOpen::BlockStyler::Group* tabPage;
    NXOpen::BlockStyler::IntegerBlock* integerParticleNumber;// Block type: Integer
    NXOpen::BlockStyler::DoubleBlock* doublePorousRatio;// Block type: Double
    NXOpen::BlockStyler::Toggle* toggleUsePorousRatio;// Block type: Toggle
    NXOpen::BlockStyler::Toggle* toggleOutFluid;// Block type: Toggle
    NXOpen::BlockStyler::Group* tabPageVoronoi;
    NXOpen::BlockStyler::IntegerBlock* integerBSplineOrder;// Block type: Integer
    NXOpen::BlockStyler::IntegerBlock* integerScaleRatio;// Block type: Integer
    NXOpen::BlockStyler::Toggle* toggleScale;// Block type: Toggle
    NXOpen::BlockStyler::Group* tabPage1;
    NXOpen::BlockStyler::ExpressionBlock* expressionRowGap;// Block type: Expression
    NXOpen::BlockStyler::ExpressionBlock* expressionColumGap;// Block type: Expression
    NXOpen::BlockStyler::Group* groupOption;// Block type: Group
    NXOpen::BlockStyler::Button* buttonGenSheet;// Block type: Button
    NXOpen::BlockStyler::Button* buttonGenParticle;// Block type: Button
    NXOpen::BlockStyler::Button* buttonTrimParticle;// Block type: Button
    NXOpen::BlockStyler::Button* buttonGen3D;// Block type: Button
    NXOpen::BlockStyler::Button* buttonOnekeyGen;// Block type: Button
    NXOpen::BlockStyler::Group* groupSet;// Block type: Group
    NXOpen::BlockStyler::Toggle* togglePrintInfo;// Block type: Toggle
    NXOpen::BlockStyler::Toggle* toggleWriteFile;// Block type: Toggle
    NXOpen::BlockStyler::FolderSelection* nativeFolderBrowser0;// Block type: NativeFolderBrowser
    
};
#endif //POROUS2D_H_INCLUDED
