//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  G:\RPWorkspace\PorousGen\UG_Dev\Application\Porous2D.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: RenPeng
//              Version: NX 1919
//              Date: 12-08-2020  (Format: mm-dd-yyyy)
//              Time: 09:59
//
//==============================================================================

#ifndef POROUS2D_H_INCLUDED
#define POROUS2D_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "HuNXOpen.h"
#include "uf_all.h"

//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport Porous2D
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    Porous2D();
    ~Porous2D();
    int Show();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the Porous2D.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);
    
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* groupShape;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enumParticleShape;// Block type: Enumeration
    NXOpen::BlockStyler::Group* groupSize;// Block type: Group
    NXOpen::BlockStyler::ExpressionBlock* expressionFaceLength;// Block type: Expression
    NXOpen::BlockStyler::ExpressionBlock* expressionFaceWidth;// Block type: Expression
    NXOpen::BlockStyler::ExpressionBlock* expressionParticleSize;// Block type: Expression
    NXOpen::BlockStyler::Group* groupParticle;// Block type: Group
    NXOpen::BlockStyler::IntegerBlock* integerParticleNumber;// Block type: Integer
    NXOpen::BlockStyler::DoubleBlock* doublePorousRatio;// Block type: Double
    
};
#endif //POROUS2D_H_INCLUDED
