#pragma once

#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BasePart.hxx>
#include <NXOpen/Face.hxx>
#include <NXOpen/Features_Extrude.hxx>
#include <NXOpen/Features_FeatureCollection.hxx>
#include <NXOpen/GenericMeasure.hxx>
#include <NXOpen/IParameterizedSurface.hxx>
#include <NXOpen/MeasureBuilder.hxx>
#include <NXOpen/MeasureFaceBuilder.hxx>
#include <NXOpen/MeasureFaces.hxx>
#include <NXOpen/MeasureManager.hxx>
#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>
#include <NXOpen/SelectDisplayableObjectList.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/Session.hxx>
#include <NXOpen/Unit.hxx>
#include <NXOpen/UnitCollection.hxx>
#include <NXOpen/LoadOptions.hxx>
#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>
#include <NXOpen/PartLoadStatus.hxx>
#include <NXOpen/Assemblies_Arrangement.hxx>
#include <NXOpen/Assemblies_ArrangementCollection.hxx>
#include <NXOpen/Assemblies_Component.hxx>
#include <NXOpen/Assemblies_ComponentAssembly.hxx>
#include <NXOpen/Face.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/Session.hxx>
#include <NXOpen/Axis.hxx>
#include <NXOpen/Body.hxx>
#include <NXOpen/BodyCollection.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/Direction.hxx>
#include <NXOpen/DirectionCollection.hxx>
#include <NXOpen/Edge.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/ExpressionCollection.hxx>
#include <NXOpen/Face.hxx>
#include <NXOpen/Features_Brep.hxx>
#include <NXOpen/Features_CylinderBuilder.hxx>
#include <NXOpen/Features_FeatureCollection.hxx>
#include <NXOpen/GeometricUtilities_BooleanOperation.hxx>
#include <NXOpen/NXObject.hxx>
#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>
#include <NXOpen/Point.hxx>
#include <NXOpen/PointCollection.hxx>
#include <NXOpen/Preferences_PartModeling.hxx>
#include <NXOpen/Preferences_PartPreferences.hxx>
#include <NXOpen/Scalar.hxx>
#include <NXOpen/ScalarCollection.hxx>
#include <NXOpen/SelectICurve.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/Session.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/Unit.hxx>
#include <NXOpen/Update.hxx>
#include <NXOpen/Xform.hxx>
#include <NXOpen/XformCollection.hxx>
#include <NXOpen/CoordinateSystem.hxx>
#include <NXOpen/CoordinateSystemCollection.hxx>
#include <NXOpen/Positioning_ComponentConstraint.hxx>
#include <NXOpen/Positioning_ComponentNetwork.hxx>
#include <NXOpen/Positioning_ComponentPositioner.hxx>
#include <NXOpen/Positioning_Constraint.hxx>
#include <NXOpen/Positioning_ConstraintReference.hxx>
#include <NXOpen/Positioning_Network.hxx>
#include <NXOpen/Positioning_Positioner.hxx>
#include <NXOpen/Positioning_ConstraintCollection.hxx>
#include <NXOpen/Positioning_DisplayedConstraint.hxx>
#include <NXOpen/Positioning_DisplayedConstraintCollection.hxx>
#include <NXOpen/DisplayableObject.hxx>
#include <NXOpen/DataContainer.hxx>
#include <NXOpen/DisplayManager.hxx>
#include <NXOpen/BlockStyler_Tree.hxx>
#include <NXOpen/BlockStyler_Node.hxx>
#include <NXOpen/DisplayModification.hxx>
#include <NXOpen/PartCleanup.hxx>
#include <NXOpen/NXObjectManager.hxx>
#include <NXOpen/Line.hxx>
#include <NXOpen/LineCollection.hxx>
#include <NXOpen/NXObject.hxx>
#include <NXOpen/INXObject.hxx>
#include <NXOpen/Preferences_SessionAssemblies.hxx>
#include <NXOpen/Preferences_SessionPreferences.hxx>
#include <NXOpen/Assemblies_ConstraintDisplayBuilder.hxx>
#include <NXOpen/FileNew.hxx>
#include <NXOpen/NavigatorFilter.hxx>
#include <NXOpen/Arc.hxx>
#include <NXOpen/ArcCollection.hxx>
#include <NXOpen/ArcValidator.hxx>
#include <NXOpen/ASCImporter.hxx>
#include <NXOpen/AssembliesUtils.hxx>
#include <NXOpen/Assemblies_ArrangementsBuilder.hxx>
#include <NXOpen/Assemblies_Assembly.hxx>
#include <NXOpen/Assemblies_AssemblyManager.hxx>
#include <NXOpen/Assemblies_ComponentGroup.hxx>
#include <NXOpen/Assemblies_ComponentGroupCollection.hxx>
#include <NXOpen/Assemblies_CreateNewComponentBuilder.hxx>
#include <NXOpen/Assemblies_Explosion.hxx>
#include <NXOpen/Assemblies_ExplosionCollection.hxx>
#include <NXOpen/Assemblies_HideComponentBuilder.hxx>
#include <NXOpen/Assemblies_LoadInterpartDataBuilder.hxx>
#include <NXOpen/Assemblies_ProductInterface_Collection.hxx>
#include <NXOpen/Assemblies_ProductInterface_InterfaceObject.hxx>
#include <NXOpen/Assemblies_ProductInterface_ObjectBuilder.hxx>
#include <NXOpen/Assemblies_ProductOutlineBuilder.hxx>
#include <NXOpen/Assemblies_ProductOutlineManager.hxx>
#include <NXOpen/Assemblies_RelinkerBuilder.hxx>
#include <NXOpen/Assemblies_RelinkerCollection.hxx>
#include <NXOpen/Assemblies_ReplaceComponentBuilder.hxx>
#include <NXOpen/Assemblies_SelectComponent.hxx>
#include <NXOpen/Assemblies_SelectComponentList.hxx>
#include <NXOpen/Assemblies_ShowComponentBuilder.hxx>
#include <NXOpen/Assemblies_UpdateStructureBuilder.hxx>
#include <NXOpen/Assemblies_WaveQuery.hxx>
#include <NXOpen/AssemDebugSession.hxx>
#include <NXOpen/AutomaticTraceline.hxx>
#include <NXOpen/AutotestExecuteBuilder.hxx>
#include <NXOpen/AutotestPreferencesBuilder.hxx>
#include <NXOpen/AutotestPrint.hxx>
#include <NXOpen/Axis.hxx>
#include <NXOpen/AxisCollection.hxx>
#include <NXOpen/BaseSession.hxx>
#include <NXOpen/BcurveValidator.hxx>
#include <NXOpen/BlockStylerDebugSession.hxx>
#include <NXOpen/BlockStyler_CompositeBlock.hxx>
#include <NXOpen/BlockStyler_ListBox.hxx>
#include <NXOpen/BlockStyler_Separator.hxx>
#include <NXOpen/BlockStyler_SetList.hxx>
#include <NXOpen/BlockStyler_TreeListMenu.hxx>
#include <NXOpen/BlockStyler_Wizard.hxx>
#include <NXOpen/Body.hxx>
#include <NXOpen/BodyCollection.hxx>
#include <NXOpen/BodyDes_OnestepUnform.hxx>
#include <NXOpen/BodyDes_OnestepUnformBuilder.hxx>
#include <NXOpen/BodyDes_OnestepUnformCollection.hxx>
#include <NXOpen/BodyDumbRule.hxx>
#include <NXOpen/BodyFeatureRule.hxx>
#include <NXOpen/BodyGroupRule.hxx>
#include <NXOpen/BodyList.hxx>
#include <NXOpen/BodyValidator.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/CallbackTest.hxx>
#include <NXOpen/CallbackTestNamespace_Subspace_CallbackTransientObj.hxx>
#include <NXOpen/CallbackTestNamespace_Subspace_CallbackTransientObjB.hxx>
#include <NXOpen/CallbackTestPointer.hxx>
#include <NXOpen/CartesianCoordinateSystem.hxx>
#include <NXOpen/Catiav4Creator.hxx>
#include <NXOpen/Catiav4Importer.hxx>
#include <NXOpen/Catiav5Creator.hxx>
#include <NXOpen/Catiav5Importer.hxx>
#include <NXOpen/CDF.hxx>
#include <NXOpen/CGMBuilder.hxx>
#include <NXOpen/ClipboardOperationsManager.hxx>
#include <NXOpen/ColorDefinition.hxx>
#include <NXOpen/ColorManager.hxx>
#include <NXOpen/ColorWidth.hxx>
#include <NXOpen/Conic.hxx>
#include <NXOpen/ConvertToFromReferenceBuilder.hxx>
#include <NXOpen/CoordinateSystem.hxx>
#include <NXOpen/CoordinateSystemCollection.hxx>
#include <NXOpen/Curve.hxx>
#include <NXOpen/CurveCollection.hxx>
#include <NXOpen/CurveDumbRule.hxx>
#include <NXOpen/CurveFeatureChainRule.hxx>
#include <NXOpen/CurveFeatureRule.hxx>
#include <NXOpen/CurveFeatureTangentRule.hxx>
#include <NXOpen/CurveGroupRule.hxx>
#include <NXOpen/CurveValidator.hxx>
#include <NXOpen/CustomPopupMenu.hxx>
#include <NXOpen/CustomPopupMenuHandler.hxx>
#include <NXOpen/CustomPopupMenuItem.hxx>
#include <NXOpen/CustomSymbols.hxx>
#include <NXOpen/CustomWidth.hxx>
#include <NXOpen/CutView.hxx>
#include <NXOpen/CutViewCollection.hxx>
#include <NXOpen/CylindricalCoordinateSystem.hxx>
#include <NXOpen/DatumAxis.hxx>
#include <NXOpen/DatumCollection.hxx>
#include <NXOpen/DatumConstraint.hxx>
#include <NXOpen/DatumPlane.hxx>
#include <NXOpen/DebugSession.hxx>
#include <NXOpen/DebugUI.hxx>
#include <NXOpen/Decal.hxx>
#include <NXOpen/DexManager.hxx>
#include <NXOpen/Dimensions.hxx>
#include <NXOpen/Direction.hxx>
#include <NXOpen/DirectionCollection.hxx>
#include <NXOpen/Display_Background.hxx>
#include <NXOpen/Display_BoundedGrid.hxx>
#include <NXOpen/Display_BoundedGridBuilder.hxx>
#include <NXOpen/Display_Camera.hxx>
#include <NXOpen/Display_CameraBuilder.hxx>
#include <NXOpen/Display_CameraCollection.hxx>
#include <NXOpen/Display_CgfxAttr.hxx>
#include <NXOpen/Display_CgfxAttrCollection.hxx>
#include <NXOpen/Display_CgfxAttributeValueColor3Builder.hxx>
#include <NXOpen/Display_CgfxAttributeValueColor4Builder.hxx>
#include <NXOpen/Display_CgfxAttributeValueFileBuilder.hxx>
#include <NXOpen/Display_CgfxAttributeValueFloat3Builder.hxx>
#include <NXOpen/Display_CgfxAttributeValueFloat4Builder.hxx>
#include <NXOpen/Display_CgfxAttributeValueIntegerBuilder.hxx>
#include <NXOpen/Display_CgfxAttributeValueNumberBuilder.hxx>
#include <NXOpen/Display_CgfxMattex.hxx>
#include <NXOpen/Display_CgfxMattexBuilder.hxx>
#include <NXOpen/Display_CgfxMattexCollection.hxx>
#include <NXOpen/Display_DatumPlaneGrid.hxx>
#include <NXOpen/Display_DatumPlaneGridBuilder.hxx>
#include <NXOpen/Display_DecalBuilder.hxx>
#include <NXOpen/Display_DecalCollection.hxx>
#include <NXOpen/Display_DynamicSection.hxx>
#include <NXOpen/Display_DynamicSectionBuilder.hxx>
#include <NXOpen/Display_DynamicSectionCollection.hxx>
#include <NXOpen/Display_DynamicSectionTypes.hxx>
#include <NXOpen/Display_ExtractScene.hxx>
#include <NXOpen/Display_Grid.hxx>
#include <NXOpen/Display_GridBuilder.hxx>
#include <NXOpen/Display_GridCollection.hxx>
#include <NXOpen/Display_Image.hxx>
#include <NXOpen/Display_ImageBasedLighting.hxx>
#include <NXOpen/Display_LightBuilder.hxx>
#include <NXOpen/Display_Lighting.hxx>
#include <NXOpen/Display_LightTypes.hxx>
#include <NXOpen/Display_NonProportionalZoom.hxx>
#include <NXOpen/Display_PlaneGrid.hxx>
#include <NXOpen/Display_PlaneGridBuilder.hxx>
#include <NXOpen/Display_Reflection.hxx>
#include <NXOpen/Display_Scene.hxx>
#include <NXOpen/Display_SectionCurveSettingsBuilder.hxx>
#include <NXOpen/Display_SelectFontFileBuilder.hxx>
#include <NXOpen/Display_SelPref.hxx>
#include <NXOpen/Display_SelPrefCollection.hxx>
#include <NXOpen/Display_Stage.hxx>
#include <NXOpen/Display_StudioImageCaptureBuilder.hxx>
#include <NXOpen/Display_TrueShading.hxx>
#include <NXOpen/Display_TrueShadingBuilder.hxx>
#include <NXOpen/Display_TrueShadingCollection.hxx>
#include <NXOpen/Display_Wall.hxx>
#include <NXOpen/DxfdwgCreator.hxx>
#include <NXOpen/DxfdwgImporter.hxx>
#include <NXOpen/Drawings_DrawingSheet.hxx>
#include <NXOpen/Drawings_DrawingSheetBuilder.hxx>
#include <NXOpen/Edge.hxx>
#include <NXOpen/EdgeBodyRule.hxx>
#include <NXOpen/EdgeBoundaryRule.hxx>
#include <NXOpen/EdgeChainRule.hxx>
#include <NXOpen/EdgeDumbRule.hxx>
#include <NXOpen/EdgeFaceRule.hxx>
#include <NXOpen/EdgeFeatureRule.hxx>
#include <NXOpen/EdgeIntersectRule.hxx>
#include <NXOpen/EdgeMultipleSeedTangentRule.hxx>
#include <NXOpen/EdgeSheetBoundaryRule.hxx>
#include <NXOpen/EdgeTangentRule.hxx>
#include <NXOpen/EdgeVertexRule.hxx>
#include <NXOpen/EdgeVertexTangentRule.hxx>
#include <NXOpen/Ellipse.hxx>
#include <NXOpen/EllipseCollection.hxx>
#include <NXOpen/EllipseValidator.hxx>
#include <NXOpen/EndCutBlockBuilder.hxx>
#include <NXOpen/EngineeringFunction.hxx>
#include <NXOpen/ErrorInfo.hxx>
#include <NXOpen/ErrorList.hxx>
#include <NXOpen/ExpDebugSession.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/ExpressionCollection.hxx>
#include <NXOpen/ExpressionCollectorSet.hxx>
#include <NXOpen/ExpressionCollectorSetList.hxx>
#include <NXOpen/ExpressionSectionSet.hxx>
#include <NXOpen/ExpressionSectionSetList.hxx>
#include <NXOpen/ExpressionValidator.hxx>
#include <NXOpen/FaceAdjacentRule.hxx>
#include <NXOpen/FaceAllBlendRule.hxx>
#include <NXOpen/FaceAndAdjacentFacesRule.hxx>
#include <NXOpen/FaceBodyRule.hxx>
#include <NXOpen/FaceBossPocketFacesRule.hxx>
#include <NXOpen/FaceConnectedBlendRule.hxx>
#include <NXOpen/FaceDumbRule.hxx>
#include <NXOpen/FaceFeatureRule.hxx>
#include <NXOpen/FaceMergedRibFacesRule.hxx>
#include <NXOpen/FaceRegionBoundaryRule.hxx>
#include <NXOpen/FaceRegionRule.hxx>
#include <NXOpen/FaceRibFacesRule.hxx>
#include <NXOpen/FaceSlotFacesRule.hxx>
#include <NXOpen/FaceTangentRule.hxx>
#include <NXOpen/Facet_BestFitAlignBuilder.hxx>
#include <NXOpen/Facet_CurvatureBuilder.hxx>
#include <NXOpen/Facet_DecimateFacetBodyBuilder.hxx>
#include <NXOpen/Facet_FacetedBody.hxx>
#include <NXOpen/Facet_FacetedBodyCollection.hxx>
#include <NXOpen/Facet_FacetedEdge.hxx>
#include <NXOpen/Facet_FacetedFace.hxx>
#include <NXOpen/Facet_FeatureExtractionBuilder.hxx>
#include <NXOpen/Facet_FillHoleBuilder.hxx>
#include <NXOpen/Facet_MultiPatchAlignmentBuilder.hxx>
#include <NXOpen/Facet_SelectFacetedBody.hxx>
#include <NXOpen/Facet_SelectFacetedBodyList.hxx>
#include <NXOpen/Facet_SmoothFacetBodyBuilder.hxx>
#include <NXOpen/Facet_SnipFacetBodyBuilder.hxx>
#include <NXOpen/Facet_STLImportBuilder.hxx>
#include <NXOpen/Facet_SubdivideFacetBodyBuilder.hxx>
#include <NXOpen/Features_ThickenBuilder.hxx>
#include <NXOpen/FollowFilletRule.hxx>
#include <NXOpen/FontCollection.hxx>
#include <NXOpen/FourPointSurfaceBuilder.hxx>
#include <NXOpen/GatewayDebugSession.hxx>
#include <NXOpen/Gateway_CopyCutBuilder.hxx>
#include <NXOpen/Gateway_ImageCaptureBuilder.hxx>
#include <NXOpen/Gateway_ImageCaptureManager.hxx>
#include <NXOpen/Gateway_PasteBuilder.hxx>
#include <NXOpen/Gdts.hxx>
#include <NXOpen/GeneralScalarTable.hxx>
#include <NXOpen/GenericMeasure.hxx>
#include <NXOpen/Group.hxx>
#include <NXOpen/GroupBuilder.hxx>
#include <NXOpen/HumanData.hxx>
#include <NXOpen/HumanHandShapeData.hxx>
#include <NXOpen/HumanPosturePrediction.hxx>
#include <NXOpen/HumanPosturePredictionBuilder.hxx>
#include <NXOpen/HumanReachZone.hxx>
#include <NXOpen/Hyperbola.hxx>
#include <NXOpen/HyperbolaCollection.hxx>
#include <NXOpen/HyperbolaValidator.hxx>
#include <NXOpen/IBaseCurve.hxx>
#include <NXOpen/IBasePlane.hxx>
#include <NXOpen/IBody.hxx>
#include <NXOpen/ICurve.hxx>
#include <NXOpen/IFitTo.hxx>
#include <NXOpen/IgesCreator.hxx>
#include <NXOpen/IgesImporter.hxx>
#include <NXOpen/ILocation.hxx>
#include <NXOpen/Importer.hxx>
#include <NXOpen/ImportManager.hxx>
#include <NXOpen/InferredConstraintsBuilder.hxx>
#include <NXOpen/InferSnapType.hxx>
#include <NXOpen/InfiniteLine.hxx>
#include <NXOpen/InfiniteLineCollection.hxx>
#include <NXOpen/Information.hxx>
#include <NXOpen/IOMName.hxx>
#include <NXOpen/IOrientation.hxx>
#include <NXOpen/IParameterizedSurface.hxx>
#include <NXOpen/IPlane.hxx>
#include <NXOpen/IProfile.hxx>
#include <NXOpen/IReferenceAxis.hxx>
#include <NXOpen/ISketchHelpedConstraint.hxx>
#include <NXOpen/ISurface.hxx>
#include <NXOpen/IValidator.hxx>
#include <NXOpen/JamNXColor.hxx>
#include <NXOpen/JamNXColorManager.hxx>
#include <NXOpen/JamSession.hxx>
#include <NXOpen/KfTest.hxx>
#include <NXOpen/Layer.hxx>
#include <NXOpen/Layer_Category.hxx>
#include <NXOpen/Layer_CategoryCollection.hxx>
#include <NXOpen/Layer_LayerManager.hxx>
#include <NXOpen/Layer_StateCollection.hxx>
#include <NXOpen/Layout.hxx>
#include <NXOpen/LayoutCollection.hxx>
#include <NXOpen/LayoutDefinition.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
#include <NXOpen/libnxopendebugsessioncpp_exports.hxx>
#include <NXOpen/libnxopendebuguicpp_exports.hxx>
#include <NXOpen/libnxopenjamtestcpp_exports.hxx>
#include <NXOpen/libnxopenuicpp_exports.hxx>
#include <NXOpen/LicenseManager.hxx>
#include <NXOpen/Light.hxx>
#include <NXOpen/LightCollection.hxx>
#include <NXOpen/LineValidator.hxx>
#include <NXOpen/LineWelds.hxx>
#include <NXOpen/ListingWindow.hxx>
#include <NXOpen/LogFile.hxx>
#include <NXOpen/Material.hxx>
#include <NXOpen/MaterialManager.hxx>
#include <NXOpen/MathUtils.hxx>
#include <NXOpen/MenuBar_MenuBarManager.hxx>
#include <NXOpen/MenuBar_MenuButton.hxx>
#include <NXOpen/MenuBar_MenuButtonEvent.hxx>
#include <NXOpen/MeshParameterData.hxx>
#include <NXOpen/MeshProfileString.hxx>
#include <NXOpen/ModelingAutotestPrint.hxx>
#include <NXOpen/ModelingView.hxx>
#include <NXOpen/ModelingViewCollection.hxx>
#include <NXOpen/ModelingViewHighQualityImage.hxx>
#include <NXOpen/ModlDirect_SelectBlend.hxx>
#include <NXOpen/ModlUtils_ExtractReferenceServiceBuilder.hxx>
#include <NXOpen/MovieManager.hxx>
#include <NXOpen/MovieSettingsBuilder.hxx>
#include <NXOpen/MWUpdate.hxx>
#include <NXOpen/NXColor.hxx>
#include <NXOpen/NXDeprecation.hxx>
#include <NXOpen/NXMatrix.hxx>
#include <NXOpen/NXMatrixCollection.hxx>
#include <NXOpen/NXObjectList.hxx>
#include <NXOpen/nxstring.hxx>
#include <NXOpen/NXTo2dCreator.hxx>
#include <NXOpen/ObjectList.hxx>
#include <NXOpen/ObjectSelector.hxx>
#include <NXOpen/ObjectTypeSelector.hxx>
#include <NXOpen/Offset.hxx>
#include <NXOpen/OffsetCollection.hxx>
#include <NXOpen/OMAttribute.hxx>
#include <NXOpen/OMClass.hxx>
#include <NXOpen/OMSchema.hxx>
#include <NXOpen/Options_ChangeList.hxx>
#include <NXOpen/Options_DraftingStandardChangeList.hxx>
#include <NXOpen/Options_OptionsManager.hxx>
#include <NXOpen/Parabola.hxx>
#include <NXOpen/ParabolaCollection.hxx>
#include <NXOpen/ParabolaValidator.hxx>
#include <NXOpen/PartCloseResponses.hxx>
#include <NXOpen/PartCloseStatus.hxx>
#include <NXOpen/PartDelayedUpdateStatus.hxx>
#include <NXOpen/PartFamilyManager.hxx>
#include <NXOpen/PartFamilyMemberData.hxx>
#include <NXOpen/PartFamilyMemberValues.hxx>
#include <NXOpen/PartImporter.hxx>
#include <NXOpen/PartReopenReport.hxx>
#include <NXOpen/PartReopenStatus.hxx>
#include <NXOpen/PartSaveOptions.hxx>
#include <NXOpen/PartSaveStatus.hxx>
#include <NXOpen/PasteSpecialBuilder.hxx>
#include <NXOpen/PerformanceManager.hxx>
#include <NXOpen/PerformanceManagerAutotestPrint.hxx>
#include <NXOpen/Plane.hxx>
#include <NXOpen/PlaneCollection.hxx>
#include <NXOpen/PlaneList.hxx>
#include <NXOpen/PlaneTypes.hxx>
#include <NXOpen/PlotBuilder.hxx>
#include <NXOpen/PlotColorsWidthsBuilder.hxx>
#include <NXOpen/PlotManager.hxx>
#include <NXOpen/PlotSourceBuilder.hxx>
#include <NXOpen/Point.hxx>
#include <NXOpen/PointCollection.hxx>
#include <NXOpen/PointList.hxx>
#include <NXOpen/PointValidator.hxx>
#include <NXOpen/PositioningDimension.hxx>
#include <NXOpen/Positioning_MatingConverter.hxx>
#include <NXOpen/PrintBuilder.hxx>
#include <NXOpen/PrintPDFBuilder.hxx>
#include <NXOpen/ProeImporter.hxx>
#include <NXOpen/PropertyContainer.hxx>
#include <NXOpen/ReferenceSet.hxx>
#include <NXOpen/RegionBoundaryRule.hxx>
#include <NXOpen/RegionPoint.hxx>
#include <NXOpen/RegionPointList.hxx>
#include <NXOpen/RemoteUtilities.hxx>
#include <NXOpen/RuleManager.hxx>
#include <NXOpen/SaveOptions.hxx>
#include <NXOpen/Scalar.hxx>
#include <NXOpen/ScalarCollection.hxx>
#include <NXOpen/ScalarMatrixValue.hxx>
#include <NXOpen/ScalarTableValue.hxx>
#include <NXOpen/ScCollector.hxx>
#include <NXOpen/ScCollectorCollection.hxx>
#include <NXOpen/ScRuleFactory.hxx>
#include <NXOpen/Section.hxx>
#include <NXOpen/SectionCollection.hxx>
#include <NXOpen/SectionData.hxx>
#include <NXOpen/SectionElementData.hxx>
#include <NXOpen/SectionInternal.hxx>
#include <NXOpen/SectionList.hxx>
#include <NXOpen/SelectBody.hxx>
#include <NXOpen/SelectBodyList.hxx>
#include <NXOpen/SelectCartesianCoordinateSystem.hxx>
#include <NXOpen/SelectCoordinateSystem.hxx>
#include <NXOpen/SelectCurve.hxx>
#include <NXOpen/SelectCurveList.hxx>
#include <NXOpen/SelectDatumPlane.hxx>
#include <NXOpen/SelectDatumPlaneList.hxx>
#include <NXOpen/SelectDisplayableObject.hxx>
#include <NXOpen/SelectDisplayableObjectList.hxx>
#include <NXOpen/SelectEdge.hxx>
#include <NXOpen/SelectEdgeList.hxx>
#include <NXOpen/SelectFace.hxx>
#include <NXOpen/SelectFaceList.hxx>
#include <NXOpen/SelectGroup.hxx>
#include <NXOpen/SelectIBaseCurve.hxx>
#include <NXOpen/SelectIBaseCurveList.hxx>
#include <NXOpen/SelectICurve.hxx>
#include <NXOpen/SelectICurveList.hxx>
#include <NXOpen/Selection.hxx>
#include <NXOpen/SelectionHandle.hxx>
#include <NXOpen/SelectionIntentRule.hxx>
#include <NXOpen/SelectionMethod.hxx>
#include <NXOpen/SelectIParameterizedSurface.hxx>
#include <NXOpen/SelectIParameterizedSurfaceList.hxx>
#include <NXOpen/SelectIReferenceAxis.hxx>
#include <NXOpen/SelectISurface.hxx>
#include <NXOpen/SelectLine.hxx>
#include <NXOpen/SelectNXObject.hxx>
#include <NXOpen/SelectNXObjectList.hxx>
#include <NXOpen/SelectObject.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/SelectPartList.hxx>
#include <NXOpen/SelectPoint.hxx>
#include <NXOpen/SelectPointList.hxx>
#include <NXOpen/SelectSketch.hxx>
#include <NXOpen/SelectSplineList.hxx>
#include <NXOpen/SelectTaggedObject.hxx>
#include <NXOpen/SelectTaggedObjectList.hxx>
#include <NXOpen/SelectView.hxx>
#include <NXOpen/ShapeSearch_SearchManager.hxx>
#include <NXOpen/ShapeSearch_ShapeSearchBuilder.hxx>
#include <NXOpen/SheetmetalFeatureProperty.hxx>
#include <NXOpen/SheetMetal_FlatPatternSettings.hxx>
#include <NXOpen/SingleMeasure.hxx>
#include <NXOpen/SmartObject.hxx>
#include <NXOpen/SphericalCoordinateSystem.hxx>
#include <NXOpen/Spline.hxx>
#include <NXOpen/SplineCollection.hxx>
//#include <NXOpen/Step203Creator.hxx>
#include <NXOpen/Step203Importer.hxx>
//#include <NXOpen/Step214Creator.hxx>
#include <NXOpen/Step214Importer.hxx>
#include <NXOpen/STLImporter.hxx>
#include <NXOpen/SuppressByExpressionBuilder.hxx>
#include <NXOpen/SurfaceRebuildData.hxx>
#include <NXOpen/SymbolFont.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/TaggedObjectCollection.hxx>
#include <NXOpen/TaggedObjectList.hxx>
#include <NXOpen/Traceline.hxx>
#include <NXOpen/TracelineCollection.hxx>
#include <NXOpen/TransientObject.hxx>
#include <NXOpen/TreeListNode.hxx>
#include <NXOpen/type.hxx>
#include <NXOpen/ugmath.hxx>
#include <NXOpen/Unit.hxx>
#include <NXOpen/UnitCollection.hxx>
#include <NXOpen/Update.hxx>
#include <NXOpen/UserDefinedObjects_UserDefinedClass.hxx>
#include <NXOpen/UserDefinedObjects_UserDefinedClassManager.hxx>
#include <NXOpen/UserDefinedObjects_UserDefinedDisplayEvent.hxx>
#include <NXOpen/UserDefinedObjects_UserDefinedEvent.hxx>
#include <NXOpen/UserDefinedObjects_UserDefinedLinkEvent.hxx>
#include <NXOpen/UserDefinedObjects_UserDefinedObject.hxx>
#include <NXOpen/UserDefinedObjects_UserDefinedObjectDisplayContext.hxx>
#include <NXOpen/UserDefinedObjects_UserDefinedObjectManager.hxx>
#include <NXOpen/View.hxx>
#include <NXOpen/ViewCollection.hxx>
#include <NXOpen/ViewDependentDisplayManager.hxx>
#include <NXOpen/VRMLImporter.hxx>
#include <NXOpen/WCS.hxx>

#include <NXOpen/WidthDefinition.hxx>
#include <NXOpen/Xform.hxx>
#include <NXOpen/XformCollection.hxx>
#include <NXOpen/Features_HolePackage.hxx>
#include <NXOpen/Features_HolePackageBuilder.hxx>
#include <NXOpen/Features_FeatureCollection.hxx>
#include <NXOpen/Features_PointFeatureBuilder.hxx>
#include <NXOpen/Features_Feature.hxx>
#include <NXOpen/PDM_PartBuilder.hxx>
#include <NXOpen/PDM_DatabaseAttributeManager.hxx>
#include <NXOpen/PDM_PdmPart.hxx>
#include <NXOpen/Features_DatumCsysBuilder.hxx>
#include <NXOpen/Features_DatumCsys.hxx>

#include <NXOpen/Features_Brep.hxx>
#include <NXOpen/Features_ExtrudeBuilder.hxx>
#include <NXOpen/Features_Feature.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/Features_FeatureCollection.hxx>
#include <NXOpen/GeometricUtilities_BooleanOperation.hxx>
#include <NXOpen/GeometricUtilities_Extend.hxx>
#include <NXOpen/GeometricUtilities_FeatureOffset.hxx>
#include <NXOpen/GeometricUtilities_FeatureOptions.hxx>
#include <NXOpen/GeometricUtilities_Limits.hxx>
#include <NXOpen/GeometricUtilities_MultiDraft.hxx>
#include <NXOpen/GeometricUtilities_SimpleDraft.hxx>
//#include <NXOpen/GeometricUtilities_SmartVolumeProfileBuilder.hxx>

#include <NXOpen/DatumPlane.hxx>
#include <NXOpen/Features_DatumPlaneBuilder.hxx>
#include <NXOpen/Features_DatumPlaneFeature.hxx>
#include <NXOpen/Features_BaseFeatureCollection.hxx>
#include <NXOpen/Features_Brep.hxx>
#include <NXOpen/Features_FeatureCollection.hxx>
#include <NXOpen/Features_MoveObjectBuilder.hxx>
#include <NXOpen/Features_BooleanBuilder.hxx>
#include <NXOpen/GeometricUtilities_BooleanOperation.hxx>
#include <NXOpen/Features_BlockFeatureBuilder.hxx>
#include <NXOpen/Features_GeomcopyBuilder.hxx>

#include <NXOpen/FaceTangentRule.hxx>
#include <NXOpen/ScRuleFactory.hxx>
#include <NXOpen/ScCollector.hxx>
#include <NXOpen/ScCollectorCollection.hxx>
#include <NXOpen/SelectionIntentRule.hxx>

//Add by RP
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_SpecifyPlane.hxx>
#include <NXOpen/BlockStyler_SpecifyPoint.hxx>
#include <NXOpen/BlockStyler_Enumeration.hxx>
#include <NXOpen/BlockStyler_ExpressionBlock.hxx>
#include <NXOpen/BlockStyler_IntegerBlock.hxx>
#include <NXOpen/BlockStyler_DoubleBlock.hxx>
#include <NXOpen/BlockStyler_Button.hxx>
#include <NXOpen/Features_AssociativeArcBuilder.hxx>
#include <NXOpen/Features_AssociativeArc.hxx>
#include <NXOpen/GeometricUtilities_CurveExtendData.hxx>
#include <NXOpen/GeometricUtilities_CurveLimitsData.hxx>
#include <NXOpen/GeometricUtilities_SupportPlaneData.hxx>
#include <NXOpen/Features_TrimSheetBuilder.hxx>
#include <NXOpen/BlockStyler_TabControl.hxx>
#include <NXOpen/BlockStyler_Toggle.hxx>
#include <NXOpen/Features_StudioSplineBuilderEx.hxx>
#include <NXOpen/GeometricUtilities_SplineExtensionBuilder.hxx>
#include <NXOpen/Features_StudioSpline.hxx>
#include <NXOpen/BlockStyler_FolderSelection.hxx>

#if UG_VERION>75
#include <NXOpen/Annotations_FrameBarElementStyleBuilder.hxx>
#include <NXOpen/Annotations_FrameBarStyleBuilder.hxx>
#include <NXOpen/Features_IsoparametricCurvesBuilder.hxx>
#include <NXOpen/Tooling_CreateBoxBuilder.hxx>
#include <NXOpen/Tooling_CreateBoxCollection.hxx>
#include <NXOpen/Tooling_ToolingSession.hxx>
#include <NXOpen/Tooling_SpreadsheetData.hxx>
#include <NXOpen/Tooling_SpreadsheetDataParameter.hxx>
#include <NXOpen/Features_StudioSplineBuilderEx.hxx>
#include <NXOpen/GeometricUtilities_SplineExtensionBuilder.hxx>
#endif


using namespace NXOpen;
